name: generate pacman game

on:
  schedule:
    # every 24 hours
    - cron: "0 */24 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # On changes
  push:
    branches:
      - main

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: abozanona/pacman-contribution-graph@main
        id: pacman-gif
        with:
            github_user_name: ${{ github.repository_owner }}
            outputs: |
                dist/pacman-contribution-graph.svg
                dist/pacman-contribution-graph-dark.svg
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git status
	  
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
            target_branch: output
            build_dir: dist
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
