name: Generate Pac-Man

on:
  schedule:
    # every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Generate Pac-Man SVGs into ./dist
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        id: pacman-gif
        with:
          # Set the username explicitly so the game uses DandelionBold's graph
          github_user_name: ${{ github.repository_owner }}

      # Publish ./dist to the "output" branch (created automatically if missing)
      - name: Publish Pac-Man SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
